name: Build, Push, and Deploy Chat Langchain

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    environment: Production
    env:
      VERCEL_TOKEN: Uepe4LUI0cFRzOqT91cLFWNL
      # VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_ORG_ID: nYyzckz1HEVq4J8w5L3ptlt1
      # VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_PROJECT_ID: 9SAYAkWvz8NCjIJN58bV3j6v
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
